### PR TITLE
cleanup. add new grid, show double-clicked lines on canvas

### PR DESCRIPTION
**Pull request by ronlawrence3**
I added ag-grid and some visualization (highlight lines when double-clicked)... still WIP, but wanted to get feedback on it and see if you think this is a good idea.

Updated to allow row selection and running of calibration with subsets of the data

### CODE REVIEW

**Comment by ronlawrence3** [comment]
I think this works pretty well. LMK what you think.

**Comment by etskinner** [comment]
Seems great! I like that Netlify gives us a preview site of the deployment. I'm gonna look at it later this evening, but I'll just give you merge permission too

**Comment by etskinner** [comment]
Is it just me, or is the Compute button missing now?
Screenshot_20240414_191912_Chrome

**Comment by etskinner** [comment]
Okay, I see why you took out the compute button, since you have several buttons on the calibration table now. I added it back for now since the instructions refer to it (and it's easier to see on mobile), hope you don't mind. I could be convinced to remove it if you care a lot, though

**Review by etskinner — APPROVED** [review]

**Comment by ronlawrence3** [comment]
Thanks. looks good to me

**Pull request merged**
